[mypy]
python_version = 3.10
exclude = (?x)(
    ^frontend/
    | ^marketing/
    | ^docs/
    | ^data/
    | ^backend/alembic/
    | __pycache__
    )
plugins = pydantic.mypy

[mypy-sqlalchemy.*]
ignore_missing_imports = True

[mypy-geoalchemy2.*]
ignore_missing_imports = True

[mypy-app.etl.transform]
disable_error_code = call-overload,arg-type

[mypy-app.etl.ssp_sp]
disable_error_code = no-any-return

[mypy-app.etl.export_static_frontend]
disable_error_code = call-overload,arg-type,no-any-return

[mypy-app.services.analytics]
disable_error_code = call-overload,arg-type,assignment,attr-defined,no-any-return,return-value

[mypy-app.services.isp_repository]
disable_error_code = arg-type,no-any-return

[mypy-app.services.population_repository]
disable_error_code = call-overload,misc,no-any-return,return-value

[mypy-app.services.territory_repository]
disable_error_code = call-overload,no-any-return
