ANALYSIS_START_YEAR = 2000

CISP_TO_UNIDADE_TERRITORIAL = {
    9: "Catete, Cosme Velho, Flamengo, Glória e Laranjeiras",
    10: "Botafogo, Humaitá e Urca",
    23: "Cachambi, Méier (parte) e Todos os Santos (parte)",
    24: "Abolição, Água Santa (parte), Encantado, Engenho de Dentro (parte), Pilares e Piedade",
    25: "Engenho Novo, Jacaré, Jacarezinho, Riachuelo, Rocha, Sampaio e São Francisco Xavier",
    26: "Água Santa (parte), Engenho de Dentro (parte), Lins de Vasconcelos e Todos os Santos",
    44: "Del Castilho, Engenho da Rainha, Inhaúma, Maria da Graça e Tomás Coelho",
    6: "Catumbi, Cidade Nova, Estácio, Rio Comprido e Centro (parte)",
    17: "Caju, Mangueira, São Cristóvão e Vasco da Gama",
    1: "Centro (parte)",
    4: "Centro (parte), Gamboa, Santo Cristo e Saúde",
    5: "Centro (parte), Lapa e Paquetá",
    7: "Santa Teresa",
    18: "Maracanã, Praça da Bandeira e Tijuca (parte)",
    19: "Alto da Boa Vista e Tijuca (parte)",
    20: "Andaraí, Grajaú e Vila Isabel",
    22: "Brás de Pina (parte), Olaria, Penha e Penha Circular (parte)",
    38: "Brás de Pina (parte), Cordovil, Jardim América, Parada de Lucas,Penha Circular (parte) e Vigário Geral",
    37: "Bancários, Cacuia, Cidade Universitária, Cocotá, Freguesia, Galeão, Jardim Carioca, Jardim Guanabara, Moneró, Pitangueiras, Portuguesa, Praia da Bandeira, Ribeira, Tauá e Zumbi",
    12: "Copacabana (parte) e Leme",
    13: "Copacabana (parte)",
    21: "Benfica, Bonsucesso, Higienópolis, Manguinhos, Maré e Ramos",
    11: "Rocinha",
    14: "Ipanema e Leblon",
    15: "Gávea, Jardim Botânico, Lagoa, São Conrado e Vidigal",
    29: "Cavalcanti, Engenheiro Leal, Madureira, Turiaçu, Vaz Lobo, Oswaldo Cruz (parte), Cascadura e Quintino Bocaiúva",
    30: "Bento Ribeiro, Campinho, Marechal Hermes e Oswaldo Cruz (parte)",
    40: "Coelho Neto, Colégio (parte), Honório Gurgel e Rocha Miranda",
    33: "Campo dos Afonsos, Deodoro, Jardim Sulacap, Magalhães Bastos, Realengo e Vila Militar",
    34: "Bangu, Gericinó, Padre Miguel e Senador Camará",
    28: "Vila Valqueire, Praça Seca e Tanque (parte)",
    32: "Anil, Cidade de Deus, Curicica, Gardênia Azul, Jacarepaguá e Taquara",
    41: "Freguesia (Jacarepaguá), Pechincha e Tanque (parte)",
    36: "Paciência e Santa Cruz",
    43: "Guaratiba, Pedra de Guaratiba e Sepetiba",
    16: "Barra da Tijuca, Itanhangá, Joá",
    42: "Recreio dos Bandeirantes, Barra de Guaratiba, Camorim, Grumari, Vargem Grande e Vargem Pequena",
    35: "Campo Grande, Cosmos, Inhoaíba, Santíssimo e Senador Vasconcelos",
    27: "Colégio (parte), Irajá, Vicente de Carvalho, Vila Kosmos, Vila da Penha e Vista Alegre",
    31: "Anchieta, Guadalupe, Parque Anchieta e Ricardo de Albuquerque",
    39: "Acari, Barros Filho, Costa Barros, Parque Colúmbia e Pavuna",
    59: "Duque de Caxias (Centro)",
    60: "Campos Elyseos",
    61: "Xerém",
    62: "Imbariê",
    52: "Centro",
    53: "Mesquita, Chatuba e Banco de Areia",
    56: "Comendador Soares, Cabuçú e Km32",
    57: "Nilópolis e Olinda",
    58: "Posse, Austin, Miguel Couto, Vila de Cava e Tinguá",
    64: "São João de Meriti, Coelho da Rocha e São Mateus",
    48: "Seropédica",
    50: "Itaguaí e Ibituporanga",
    51: "Paracambi",
    55: "Centro, Norte, Sul. Leste, Oeste e Nordeste",
    63: "Japeri, Engenheiro Pedreira, Marajoara, Pedra Lisa e Rio D`Ouro",
    65: "Magé, Santo Aleixo e Suruí",
    66: "Inhomirim e Guia de Copaíba",
    67: "Guapimirim",
    54: "Areia Branca, Jardim Redentor, Parque São José, Nova Aurora e Lote XV",
    72: "São Gonçalo",
    73: "Neves",
    74: "Monjolo",
    75: "Ipiiba e Sete Pontes",
    76: "Centro, Ponta da Areia, Ilha da Conceição, São Lourenço, Fátima, Morro do Estado, Ingá, São Domingos, Gragoatá e Boa Viagem",
    77: "Santa Rosa, Icaraí, Vital Brasil, Pé Pequeno, Viradouro e Cubango",
    78: "Fonseca, Viçoso Jardim, Caramujo, Baldeador, Santa Bárbara, Tenente Jardim, Engenhoca, Santana e Barreto",
    79: "Jurujuba, Charitas, São Francisco, Cachoeiras, Maceió, Largo da Batalha, Ititioca, Badu, Sapê, Matapaca, Vila Progresso, Muriqui, Maria Paula e Cantagalo",
    81: "Itaipu, Camboinhas, Itacoatiara, Piratininga, Cafubá, Jacaré, Rio do Ouro, Engenho do Mato, Várzea das Moças e Jardim Imbuí",
    82: "Maricá e Inoã",
    118: "Araruama, Morro Grande e São Vicente de Paula",
    124: "Saquarema, Bacaxá e Sampaio Correia",
    125: "São Pedro da Aldeia",
    126: "Cabo Frio e Tamoios",
    127: "Armação dos Búzios",
    129: "Iguaba Grande",
    132: "Arraial do Cabo",
    70: "Tanguá",
    71: "Itaboraí, Cabuçú, Itambí, Porto das Caixas e Sambaetiba",
    119: "Rio Bonito e Boa Esperança",
    120: "Silva Jardim, Aldeia Velha, Correntezas e Gaviões",
    159: "Cachoeiras de Macacu, Japuíba e Subaio",
    88: "Barra do Piraí, Dorandia, Ipiabas, São José do Turvo e Vargem Alegre",
    91: "Valença, Barão de Juparana, Conservatória, Parapeúna, Pentagna e Santa Isabel do Rio Preto",
    92: "Rio das Flores, Manuel Duarte, Abarracamento e Taboas",
    94: "Piraí, Arrozal, Monumento e Santanésia",
    95: "Vassouras, Andrade Pinto, São Sebastião dos Ferreiros e Sebastião de Lacerda",
    96: "Paty do Alferes e Avelar",
    97: "Mendes",
    98: "Engenheiro Paulo de Frontin e Sacra Família do Tinguá",
    90: "Antonio Rocha, Floriano, Nossa Senhora do Amparo, Rialto e Regiões Administrativas I, II, III, IV, V, VI, VII, VIII, IX, X, XI, XII, XIII, XIV",
    93: "Volta Redonda",
    101: "Pinheiral",
    168: "Rio Claro, Getulândia, Lídice, Passa Três e São João Marcos",
    165: "Mangaratiba, Conceição de Jacareí, Vila Muriquí, Itacuruçá",
    166: "Angra dos Reis, Jacuecanga, Cunhambebe, Mambucaba, Abraão e Praia de Araçatiba",
    89: "Resende, Engenheiro Passos, Agulhas Negras, Pedra Selada e Fumaça",
    99: "Itatiaia",
    100: "Quatis, Falcão e Ribeirão de São Joaquim",
    104: "São José do Vale do Rio Preto",
    110: "Teresópolis, Vale do Bonsucesso e Vale do Paquequer",
    111: "Sumidouro",
    112: "Carmo, Córrego da Prata e Porto Velho do Cunha",
    107: "Paraíba do Sul, Werneck, Salutaris e Inconfidência",
    108: "Três Rios e Bemposta",
    105: "Petrópolis e Cascatinha",
    106: "Itaipava, Pedro do Rio e Posse",
    109: "Sapucaia, Anta, Pião, Nossa Senhora Aparecida e Jamapara",
    134: "Campos dos Goytacazes (Primeiro Subdistrito, Segundo Subdistrito e Quarto Subdistrito), Ibitioca, Dores de Macabu, Morangaba, Mussurepe, Serrinha, Santo Amaro de Campos, São Sebastião de Campos e Tocos",
    141: "São Fidelis, Cambiasca, Colonia, Ipuca e Pureza",
    145: "Barcelos, Atafona, São João da Barra, Grussaí, Cajueiro e Pipeiras",
    146: "Campos dos Goytacazes (Terceiro Subdistrito), Santa Maria, Morro do Coco, Santo Eduardo, Travessão e Vila Nova de Campos",
    147: "São Francisco de Itabapoana, Maniva e Barra Seca",
    138: "Laje do Muriaé",
    139: "Porciúncula, Purilândia e Santa Clara",
    140: "Varre-Sai",
    143: "São José de Ubá",
    144: "Bom Jesus de Itabapoana, Carabuçú, Calheiros, Pirapetinga de Bom Jesus, Rosal e Serrinha",
    148: "Cardoso Moreira e São Joaquim",
    121: "Casimiro de Abreu, Professor Souza, Barra de São João e Rio Dourado",
    122: "Conceição de Macabú e Macabuzinho",
    123: "Centro, Cabiúnas, Barra de Macaé, Aeroporto e Imboassica",
    128: "Rio das Ostras",
    130: "Quissamã",
    135: "Itaocara, Portela, Batatal, Laranjais, Jaguarembe e Estrada Nova",
    136: "Santo Antônio de Pádua, Campelo, Paraoquena, Monte Alegre, Ibitiguaçú, Santa Cruz, Baltazar, Marangatú e São Pedro de Alcântara",
    137: "Miracema, Venda das Flores e Paraíso do Tobias",
    142: "Cambuci, Três Irmãos, Funil, Monte Verde e São João do Paraíso",
    155: "São Sebastião do Alto, Valão do Barro e Ipituna",
    151: "Nova Friburgo, São Pedro da Serra, Lumiar, Amparo, Riograndina, Conselheiro Paulino e Campo do Coelho",
    152: "Duas Barras e Monnerat",
    153: "Cantagalo, Santa Rita da Floresta, Boa Sorte, Euclidelândia e São Sebastião do Paraíba",
    154: "Macuco",
    156: "Santa Maria Madalena, Doutor Loreti, Renascença, Santo Antônio do Imbé, Sossego e Triunfo",
    157: "Trajano de Moraes, Doutor Elias, Sodrelândia, Vila da Grama e Visconde de Imbé",
    158: "Bom Jardim, Banquete, Barra Alegre e São José do Ribeirão",
}


